Class {
	#name : #MJCCPClassTests,
	#superclass : #FAMIXEntity,
	#instVars : [
		'id',
		'numberOfLines',
		'numberOfFragments',
		'sources'
	],
	#category : #'Moose-JEE-CCProject-Tests-Model'
}

{ #category : #accessing }
MJCCPClassTests >> id [
	^ id
]

{ #category : #accessing }
MJCCPClassTests >> id: anObject [
	id := anObject
]

{ #category : #accessing }
MJCCPClassTests >> numberOfFragments [
	^ numberOfFragments
]

{ #category : #accessing }
MJCCPClassTests >> numberOfFragments: anObject [
	numberOfFragments := anObject
]

{ #category : #accessing }
MJCCPClassTests >> numberOfLines [
	^ numberOfLines
]

{ #category : #accessing }
MJCCPClassTests >> numberOfLines: anObject [
	numberOfLines := anObject
]

{ #category : #accessing }
MJCCPClassTests >> sources [
	^ sources
]

{ #category : #accessing }
MJCCPClassTests >> sources: anObject [
	sources := anObject
]
