Class {
	#name : #MJCCPSysteminfoTests,
	#superclass : #FAMIXEntity,
	#instVars : [
		'granularity',
		'maxLines',
		'minLines',
		'system',
		'threshold'
	],
	#category : #'Moose-JEE-CCProject-Tests-Model'
}

{ #category : #accessing }
MJCCPSysteminfoTests >> granularity [
	^ granularity
]

{ #category : #accessing }
MJCCPSysteminfoTests >> granularity: anObject [
	granularity := anObject
]

{ #category : #accessing }
MJCCPSysteminfoTests >> maxLines [
	^ maxLines
]

{ #category : #accessing }
MJCCPSysteminfoTests >> maxLines: anObject [
	maxLines := anObject
]

{ #category : #accessing }
MJCCPSysteminfoTests >> minLines [
	^ minLines
]

{ #category : #accessing }
MJCCPSysteminfoTests >> minLines: anObject [
	minLines := anObject
]

{ #category : #accessing }
MJCCPSysteminfoTests >> system [
	^ system
]

{ #category : #accessing }
MJCCPSysteminfoTests >> system: anObject [
	system := anObject
]

{ #category : #accessing }
MJCCPSysteminfoTests >> threshold [
	^ threshold
]

{ #category : #accessing }
MJCCPSysteminfoTests >> threshold: anObject [
	threshold := anObject
]
