Class {
	#name : #MJCCPClonesTests,
	#superclass : #FAMIXEntity,
	#instVars : [
		'systeminfo',
		'classinfo',
		'classes'
	],
	#category : #'Moose-JEE-CCProject-Tests-Model'
}

{ #category : #accessing }
MJCCPClonesTests >> classes [
	^ classes
]

{ #category : #accessing }
MJCCPClonesTests >> classes: anObject [
	classes := anObject
]

{ #category : #accessing }
MJCCPClonesTests >> classinfo [
	^ classinfo
]

{ #category : #accessing }
MJCCPClonesTests >> classinfo: anObject [
	classinfo := anObject
]

{ #category : #accessing }
MJCCPClonesTests >> systeminfo [
	^ systeminfo
]

{ #category : #accessing }
MJCCPClonesTests >> systeminfo: anObject [
	systeminfo := anObject
]
