Class {
	#name : #MJCCPSourceTests,
	#superclass : #FAMIXAssociation,
	#instVars : [
		'cloneClass',
		'codeClass'
	],
	#category : #'Moose-JEE-CCProject-Tests-Model'
}

{ #category : #accessing }
MJCCPSourceTests >> cloneClass [
	^ cloneClass
]

{ #category : #accessing }
MJCCPSourceTests >> cloneClass: anObject [
	cloneClass := anObject
]

{ #category : #accessing }
MJCCPSourceTests >> codeClass [
	^ codeClass
]

{ #category : #accessing }
MJCCPSourceTests >> codeClass: anObject [
	codeClass := anObject
]
