Class {
	#name : #MJFAMIXTableGroupTests,
	#superclass : #TestCase,
	#category : #'Moose-JEE-Tests'
}

{ #category : #'as yet unclassified' }
MJFAMIXTableGroupTests >> testComputeLevenshteinDistancesAmongTheFields [

	| mooseModel matrix |
	
	
	mooseModel := JEETestModels new sampleMooseModelContainingJustADB.
	
	self assert: (mooseModel allTables size = 3).
	self assert: (mooseModel allFKAssociations size = 2).
	self assert: (mooseModel allColumns size = 75).

	matrix := mooseModel allTables computeLevenshteinDistancesAmongTheFields.
	
	self assert: (matrix size = (76*76)).
	 
	

]
