Class {
	#name : #BusinessApplications,
	#superclass : #ApplicationDefinition,
	#category : #'Mobi-MooseEE-Architecture-Model'
}

{ #category : #'as yet unclassified' }
BusinessApplications class >> geschaeft [
	^#(
	'DB2YVIEW.VGESFPO1'
	)
]

{ #category : #'as yet unclassified' }
BusinessApplications class >> object [
	^#(
	'DB2YVIEW.VOBMFZP1'
	'DB2YVIEW.VOBMFZN1'
	'DB2YVIEW.VOBSHIP4'
	'DB2YVIEW.VOBUEB4'
	
	'DB2YVIEW.VEOMFZN1'
	'DB2YVIEW.VEOMFZP1'
	'DB2YVIEW.VEOUEB11'
	'DB2YVIEW.VEOSHIP1'
	
	'DB2YVIEW.VPA01771'
	'DB2YVIEW.VPA00282'
	'DB2YVIEW.VOBPAR1'
	'DB2YVIEW.VOBORPA1'
	'DB2YVIEW.VEM00281'
	)
]

{ #category : #'as yet unclassified' }
BusinessApplications class >> object_definition [
	^#(
	'DB2YVIEW.VEM00301'
	'DB2YVIEW.VP2SBB1'
	'DB2YVIEW.VP2SINV1'
	'DB2YVIEW.VP2ATT1'
	'DB2YVIEW.VP2ATTR1'
	'DB2YVIEW.VP2ATVR1'
	'DB2YVIEW.VP2SBBR1'
	'DB2YVIEW.VP2EXPR1'
	'DB2YVIEW.VP2TAB1'
	'DB2YVIEW.VP2TATT1'
	'DB2YVIEW.VP2TOUT1'
	'DB2YVIEW.VP2TROW1'
	'DB2YVIEW.VP2PFAT1'
	'DB2YVIEW.VP297731'
	)
]

{ #category : #'as yet unclassified' }
BusinessApplications class >> partner [
	^#()
]

{ #category : #'as yet unclassified' }
BusinessApplications class >> produkt_definition [
	^#(
	'DB2YVIEW.VED00901'
	'DB2YVIEW.VED08441'
	'DB2YVIEW.VED90001'
	'DB2YVIEW.VED09441'
	'DB2YVIEW.VED00911'
	'DB2YVIEW.VP2SBZR1'
	'DB2YVIEW.VP2SINV1'	
	'DB2YVIEW.VP2SBB1'
	'DB2YVIEW.VP2SINV1'
	'DB2YVIEW.VP2ATT1'
	'DB2YVIEW.VP2ATTR1'
	'DB2YVIEW.VP2ATVR1'
	'DB2YVIEW.VP2SBBR1'
	'DB2YVIEW.VP2EXPR1'
	'DB2YVIEW.VP2TAB1'
	'DB2YVIEW.VP2TATT1'
	'DB2YVIEW.VP2TOUT1'
	'DB2YVIEW.VP2TROW1'
	'DB2YVIEW.VP2PFAT1'
	'DB2YVIEW.VP297731'
	)
]

{ #category : #'as yet unclassified' }
BusinessApplications class >> vertrag [
	^#(
	'DB2YVIEW.VALL0800'
	'DB2YVIEW.VPA97925'
	'DB2YVIEW.VPA09412'
	'DB2YVIEW.VVERDAT1'
	'DB2YVIEW.VVERTXT1'
	'DB2YVIEW.VALL9785'
	'DB2YVIEW.VALL0801'
	'DB2YVIEW.VGESGPA2'
	'DB2YVIEW.VPA09492'
	'DB2YVIEW.VPA08095'
	'DB2YVIEW.VVERPAR1'
	'DB2YVIEW.VPB08002'
	'DB2YVIEW.VPA9792D'
	'DB2YVIEW.VVERDFZ1'
	)
]

{ #category : #'as yet unclassified' }
BusinessApplications >> seeClassSide [
]
